# Generated by Django 4.0.2 on 2022-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_newuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='關於'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='啟用'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='管理員'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=150, verbose_name='姓名'),
        ),
    ]
