# Generated by Django 4.0.2 on 2022-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_about_alter_newuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_state',
            field=models.CharField(choices=[('階段一', 'SEC404'), ('階段二', 'SEC303'), ('階段三', 'SEC202')], default='階段一', max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='電子信箱'),
        ),
    ]
